mj1618/serverless-offline-sns

README.md, package.json, src/index.ts
Found this issue running under Docker on OSX. Listening to localhost under Docker is a black hole; you need to listen to the "any" interface (0.0.0.0). Serverless-offline already supports this as a command line option; this change adds a serverless.yml parameter to set it for the SNS plugin.
=> Add "host" configuration parameter to set the interface on which to listen

README.md, package.json, src/index.ts
Matthew - take a look. I think this is the cleanest way to do it. I've updated the README to match.
=> Default to using the host specified to serverless-offline

src/index.ts
I introduced a bug in my previous pull commit. Fixed.
=> Fixed bug in createTopic (sending object rather than string)

src/index.ts, src/sns-adapter.ts
Timeouts configured in the serverless.yml file weren't being respected, since the SNS subscription was just passing the function name to the adapter (instead of the whole serverless function object). This resulted in timeouts being set to the default value of 6 seconds.
=> Pass full function object to SNS adapter so timeout is set correctly

src/sns-adapter.ts, src/sns-server.ts, test/mock/handler.ts, test/spec/sns.ts
Currently any `MessageAttributes` will be swallowed.
This change will send the `MessageAttributes` along with the message in the same format as AWS does.
It is only possible to pass `MessageAttributes` when the `MessageStructure==='raw'`, otherwise an empty object will be returned (current default).
=> add possibility to receive MessageAttributes 

src/sns-server.ts
In v0.30.0, it's only pass MessageAttribute into lambda when MessageStructure == 'raw'.
By AWS SNS developer guide, Using Amazon SNS Message Attributes, MessageStructure should be raw delivery to use MessageAttribute with SQS endpoints.
And by AWS:SNS API document, valid value of MessageStructure is 'json'. Otherwise it will be raw delivery.
So we can block MessageAttrubite passthrough only when MessageStructure !== 'json'. The behavior of simulator will more similar with production env in AWS.
=> MessageAttribute can work if MessageStructure !== 'json'

src/sns-adapter.ts
This is a bug fix for cases when sns-endpoint is given, but on actual sns the plugin tries to connect to 127.0.0.1.
=> Fix for subscribe function when snsEndpoint is given.

README.md, package-lock.json, package.json, src/index.ts, src/sns-adapter.ts, src/sns-server.ts, test/mock/handler.ts, test/spec/sns.ts
When using this plugin: https://www.npmjs.com/package/serverless-pseudo-parameters
None of the account information is being replace for account id. Psudeo params manages replace at the package level which never takes place offline.
This functionality replaces the psuedo param #{AWS::AccountId} with a customizable account id so you could ensure expected account id behavior.
=>  Adding a fix for Psuedo params

src/index.ts, src/sns-adapter.ts, test/spec/sns.ts
This PR would ensure that the `host` config option is used for the generated subscription urls.  Currently, this was only listening on the provided `host` but still using the default of `127.0.0.1` as the subscription url - which would cause the push to the subscription url to fail.
I believe this was actually the issue being reported in #23 . This is specifically necessary for me to support use in a docker compose setup where localstack is providing SNS. I need to ensure the host of the lambda container is being used for subscription urls.
Open question: Should this also attempt to fall back to `this.options.host`, to default to use the serverless-offline host if set?
=> Uses config host for subscriber urls

src/helpers.ts, src/sns-adapter.ts, src/sns-server.ts, src/types.d.ts, test/spec/sns.ts
This PR adds the missing `MessageId` in `publish()` response.
It's required by some other languages AWS SDK (JavaScript is so forgiving), hence I guess this is might be a good addition.
(I also made sure the type definition will also return a `PublishResponse` as defined in the AWS SDK)
=> Make sure publish() endpoint will return a valid PublishResponse

src/index.ts, test/mock/multi.dot.handler.ts, test/spec/sns.ts, tsconfig.json
fixes handlers in files with more than one dot in the filename not working due to the use of `String.prototype.split` when parsing out the function name from the file name.
=> fix createHandlers not working for paths with more than one dot

README.md, package-lock.json, package.json, src/sns-server.ts
This PR modifies the publishing functionality to add support for SQS subscriptions. It now checks the `Prototcol` property of the subscription, defaults to `http` if it was not set, and will now throw an error if the value is not one of `http` or `sqs` (case insensitive).
`http` subscriptions use the existing functionality with `fetch`. `sqs` subscriptions will instantiate an instance of the `aws-sdk` `SQS` client, using the protocol and host of the subscription's `Endpoint` as the `SQS` client endpoint, and the full URL of the subscription's `Endpoint` as the `QueueUrl`. As noted in the README, it is expected that the subscription is created using the full `QueueUrl` provided by SQS when creating the queue, or from `ListQueues` as the subscription endpoint.
I'm open to suggestions, but I …
=> add [experimental?] support for SQS subscriptions

package-lock.json, package.json, src/index.ts
With this any client can connect to the offline SNS.
Usecase:
Front-end app would like to subscribe to the SNS and publish to the channel. Frontend app is NOT on the same domain. SNS servers runs on localhost, frontend app runs on frontend.mycool.dev
=> Adding cors

src/index.ts
Currently, you can provide a location to the handler file folder relative to the current working directory using a [serverless-offline configuration value](https://github.com/mj1618/serverless-offline-sns/blob/master/src/index.ts#L66). However, serverless-offline also has a command-line option that this plugin isn't recognizing:
`--location              -l  The root location of the handlers' files. Defaults to the current directory`
This pull request fixes this, preferring the command-line option if one is provided.
=> Allow for the handler file location to be provided by a CLI option.

src/index.ts
```yaml
mySnsFn:
handler: src/path/to/index.handler
memorySize: 1024
timeout: 120
events:
- sns:
arn:
Ref: MySnsTopicName
topicName: my-sns-topic
```
```
Serverless: INFO[serverless-offline-sns]: Creating topic: "[object Object]" for fn "mySnsFn"
```
```
Serverless: INFO[serverless-offline-sns]: Creating topic: "my-sns-topic" for fn "mySnsFn"
```
=> Fix logging of topicName before creation

src/index.ts, test/spec/sns.ts
this checks for the proper configuration of sns if only a string is given:
```
...
events
- sns: arn:aws:sns:<region>:<AccountId>:<topic-name>
```
As documented by Serverless here:
https://serverless.com/framework/docs/providers/aws/events/sns/
this fixes an issue mentioned in issue #26
=> check for proper sns configuration if configured with string only

src/index.ts
Remove the timeout for the express server which defaults to 120 seconds. This caused some requests which took a long time to throw a "socket hang up" error. This should fix the type of errors seen in #30
=> fix(#30): Remove 120 sec default request timeout

src/sns-adapter.ts, src/sns-server.ts, test/spec/sns.ts
A SNS publish can accept a Subject for other than Email notifications and it should appear in the Sns record as "Subject" field not "subject".
=> subject field should be Subject

src/sns-adapter.ts
I noticed that when running serverless-offline-sns to call a Lambda event, the MessageId returned by sns.publish did not match the record.Sns.MessageId in the call to dispatch in the Lambda. This results in not being able to match up results between the call and its eventual response, which this simple patch fixes, and brings in line with how SNS works when run on AWS.
=> Use existing, not new, message id to pass to SNS Lambda event

src/index.ts
This resolves two issues that I found when trying to use this with the dotnetcore3.1 runtime:
- Set default for function runtime if not set at the function level. This will set the runtime to what is defined at the provider level of he serverless configuration.
- Updated createProxyHandler to return a function that returns the function handler method. This is what I believe should resolve executing non nodeJS runtimes.
I tested this locally using my fork of serverless-offline (which adds .net core support, currently a PR on their repo).
=> Fix defects.

README.md, src/index.ts
This is useful when using typescript and your .build/handler is not in the root directory.
=> Add support for custom location parameter

src/index.ts, test/spec/sns.ts
Hi! I noticed that startup fails if the resources block of serverless.yml is empty.
This seems to fix it rather than defining an empty resources block.
Let me know what you think, thanks.
=> Dont error on an empty resources block

README.md
Hello, I noticed an extra ` ``` ` in the README when reading through the docs, thought I'd submit a quick PR to fix it.
Thanks!
=> removed extra ``` from multiline code example in readme

src/index.ts
We have a number of custom resources defined in our serverless config. They aren't used for functions (DLQs) or their topics aren't discoverable by SNS Offline.
This fix makes the subscribe more defensive (as it was in previous versions) and logs that it's skipping the resource.
=> fix: only push valid subscriptions

src/index.ts
Using pathToFileURL to import handler method across OS's
=> Fix: Windows testing - file path issues when using import method

src/index.ts, test/mock/handler.ts, test/spec/sns.ts
- added a test case for default exported handlers
- introduced a fallback to use the default exported handler if the handler reference does not exist in the imported handler file (thank you @renejesusgv for bringing this to my attention)
Fixes: #191
=> #191 Now supporting default exported handlers
